### ISSUE TITLE
switch to detect for heroku.cfg

### ISSUE THREAD

**Issue by pigeonflight** [plone/heroku-buildpack-plone#12]
Currently it looks for the presence of a buildout.cfg. We should switch to detect for heroku.cfg.
This is still a problem if someone has an arbitrary *.cfg file. We'll need to cross that bridge at some point.

**Comment by zupo** [comment]
Uhm, no, I disagree. ``buildout.cfg`` is the default file that is there in most projects. However one might be using ``production.cfg`` instead of ``heroku.cfg`` and the detect script will fail to detect the app as a buildout app.
